import { useEffect, useState } from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Link from "next/link";
const Blogs = () => {
  const [postData, setpostData] = useState([]);
  const listPost = async () => {
    let response = await fetch(
      "http://localhost/wordpress-rest/wp-json/wp/v2/posts?_embed"
    );
    let res = await response.json();
    setpostData(res);
  };
  useEffect(() => {
    listPost();
  }, []);

  return (
    <>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="container">
        <div className="row">
          <h2>Blogs</h2>
        </div>
        <div className="row">
          <div className="col-md-8">
            {postData.map((item, index) => (
              <div key={index}>
                <img
                  src={item._embedded["wp:featuredmedia"][0].source_url}
                  alt=""
                  width="300"
                />
                <h3>{item.title.rendered}</h3>
                <p dangerouslySetInnerHTML={{__html: item.excerpt.rendered}} />
                <Link href={`/blogs/${item.slug}`}><a>Read More...</a></Link>
              </div>
            ))}
          </div>
          <div className="col-md-4"></div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Blogs;
